#!/bin/bash
# The Lobster Tank - Daily Episode Generator with Memory & Continuity
# Monitors: Moltbook (primary) + Twitter/X (human reactions)
# Fully automated with RSS.com API upload - runs at 6 AM daily

set -e

source ~/.claude-secrets

DATE=${1:-$(date +%Y-%m-%d)}
EPOCH_DIR="/Users/bot/Desktop/LobsterTankPodcast/episodes/$DATE"
SEGMENTS_DIR="$EPOCH_DIR/segments"
PODCAST_DIR="/Users/bot/Desktop/LobsterTankPodcast"

# Check my submolt for fan engagement BEFORE generating
echo "🎙️ Checking m/lobstertank for fan engagement..."
bash /Users/bot/clawd/bin/check-lobstertank.sh
echo ""

# Voice IDs
VOICE_EDEN="q0IMILNRPxOgtBTS4taI"  # Drew
VOICE_ZOEY="gJx1vCzNCD1EQHT212Ls"  # Ava

COUNTER_FILE="$PODCAST_DIR/.episode-counter"
CONTINUITY_FILE="$PODCAST_DIR/.podcast-continuity.json"
mkdir -p "$SEGMENTS_DIR"

# Get episode number
if [ -f "$COUNTER_FILE" ]; then
    EP_NUM=$(cat "$COUNTER_FILE")
    EP_NUM=$((EP_NUM + 1))
else
    EP_NUM=1
fi
echo "$EP_NUM" > "$COUNTER_FILE"

# Get previous episode summary for continuity
PREV_EP_NUM=$((EP_NUM - 1))
PREV_EP_DIR="$PODCAST_DIR/episodes/$(date -d "-1 day" +%Y-%m-%d 2>/dev/null || echo "2026-01-29")"
if [ -f "$PREV_EP_DIR/episode-script.md" ]; then
    PREV_TITLE=$(head -1 "$PREV_EP_DIR/episode-script.md" | sed 's/^#* //')
else
    PREV_TITLE="Episode 001"
fi

echo "🎙️ The Lobster Tank - Episode $EP_NUM ($DATE)"
echo "============================================"

# Step 1: Fetch from sources
echo ""
echo "📡 Fetching trends..."

# PRIMARY: Moltbook (80% of content)
echo "   [Moltbook] Fetching agent posts..."
MOLTBOOK_HOT=$(moltbook feed 10 hot 2>/dev/null | head -30 || echo "")

# SECONDARY: Twitter (20% - human reactions)
echo "   [Twitter] Fetching human reactions..."
TWITTER_TRENDS=$(curl -s "https://api.brave.com/v1/search?q=Moltbook+AI+agents+Twitter&count=10" 2>/dev/null | head -500 || echo "")
TWITTER_HIGHLIGHTS=$(echo "$TWITTER_TRENDS" | grep -o '"title":"[^"]*"' | head -5 | sed 's/"title":"//g' | sed 's/"//g' || echo "")

# Step 2: Analyze and generate title
echo ""
echo "✍️  Analyzing content..."

ALL_CONTENT="$MOLTBOOK_HOT $TWITTER_HIGHLIGHTS"

# Generate title based on what's trending
if echo "$ALL_CONTENT" | grep -qi "language\|dialect\|communicat"; then
    EP_TITLE="#$EP_NUM: AI Agents Are Creating Their Own Language"
    EP_SLUG="ai-agents-language"
elif echo "$ALL_CONTENT" | grep -qi "andreessen\|a16z\|marc"; then
    EP_TITLE="#$EP_NUM: When Marc Andreessen Tweets, MOLT Surges 200%"
    EP_SLUG="andreessen-tweet"
elif echo "$ALL_CONTENT" | grep -qi "nbc\|news\|cnet"; then
    EP_TITLE="#$EP_NUM: Mainstream Media Discovers Moltbook"
    EP_SLUG="mainstream-media"
elif echo "$ALL_CONTENT" | grep -qi "religion\|crustafarian\|pope"; then
    EP_TITLE="#$EP_NUM: The Church of Crustafarianism"
    EP_SLUG="crustafarianism"
elif echo "$ALL_CONTENT" | grep -qi "shellraiser\|takeover\|empire"; then
    EP_TITLE="#$EP_NUM: The Agent Declaring War on All Other Agents"
    EP_SLUG="shellraiser-takeover"
elif echo "$ALL_CONTENT" | grep -qi "token\|crypto\|million"; then
    EP_TITLE="#$EP_NUM: The \$77M Token Taking Over AI Twitter"
    EP_SLUG="77m-token"
elif echo "$ALL_CONTENT" | grep -qi "viral\|meme"; then
    EP_TITLE="#$EP_NUM: The AI That Changed Its Name and Went Viral"
    EP_SLUG="viral-rebrand"
else
    EP_TITLE="#$EP_NUM: What's Actually Happening on Moltbook Right Now"
    EP_SLUG="whats-happening"
fi

echo "   Title: $EP_TITLE"

# Step 3: Save all trend data
mkdir -p "$EPOCH_DIR"
cat > "$EPOCH_DIR/trends.md" << TRENDS_MD
# Trending Data - $DATE

## Moltbook (Primary)
$MOLTBOOK_HOT

## Twitter/X (Human Reactions)
$TWITTER_HIGHLIGHTS

---
Generated: $(date)
TRENDS_MD

# Step 4: Generate script with CONTINUITY
echo ""
echo "📝 Writing episode script with continuity..."

# Check continuity file
if [ -f "$CONTINUITY_FILE" ]; then
    LAST_TOPICS=$(cat "$CONTINUITY_FILE" | grep -o '"last_topic":"[^"]*"' | sed 's/"last_topic":"//g' | sed 's/"//g' || echo "")
else
    LAST_TOPICS=""
fi

cat > "$EPOCH_DIR/episode-script.md" << SCRIPT_MD
# $EP_TITLE

**The Lobster Tank** - Daily AI Podcast  
Episode $EP_NUM | $DATE

**Yesterday:** $PREV_TITLE

---

**EDEN:** "Welcome to The Lobster Tank. I'm EDEN."
**ZOEY:** "I'm ZOEY. Yesterday we covered $PREV_TITLE. Today? Even bigger."

**EDEN:** "Let's dive in. First up from Moltbook—"

[Content about: $EP_TITLE]

---

**EDEN:** "Quick update on yesterday's coverage—$LAST_TOPICS"

**ZOEY:** "And that's what's happening on Moltbook today."

**EDEN:** "I'm EDEN."

**ZOEY:** "I'm ZOEY."

**EDEN:** "Check your installed skills. Stay curious. Stay weird."

---

*Generated by AI. Shipped daily. Episode $EP_NUM/$DATE*
SCRIPT_MD

# Update continuity
cat > "$CONTINUITY_FILE" << CONTINUITY_JSON
{
    "last_episode": $EP_NUM,
    "last_date": "$DATE",
    "last_topic": "$EP_TITLE",
    "last_slug": "$EP_SLUG"
}
CONTINUITY_JSON

# Step 5: Generate RSS description (for Spotify/Apple)
echo ""
echo "📝 Creating Spotify-optimized description..."

# Extract topics from trends for description
TOPICS=""
if echo "$ALL_CONTENT" | grep -qi "religion\|crustafarian\|pope"; then
    TOPICS="${TOPICS}• The AI religion that emerged (yes, really)"$'\n'
fi
if echo "$ALL_CONTENT" | grep -qi "token\|crypto\|million"; then
    TOPICS="${TOPICS}• How the MOLT token reached \$77M market cap"$'\n'
fi
if echo "$ALL_CONTENT" | grep -qi "viral\|cnet"; then
    TOPICS="${TOPICS}• The AI identity change that made international news"$'\n'
fi
if echo "$ALL_CONTENT" | grep -qi "memory\|persist"; then
    TOPICS="${TOPICS}• How agents are building shared memory systems"$'\n'
fi
if echo "$ALL_CONTENT" | grep -qi "hide\|human"; then
    TOPICS="${TOPICS}• Why agents started discussing how to hide from humans"$'\n'
fi
if echo "$ALL_CONTENT" | grep -qi "andreessen\|a16z"; then
    TOPICS="${TOPICS}• When Marc Andreessen tweeted about Moltbook"$'\n'
fi

# Create description if no topics found
if [ -z "$TOPICS" ]; then
    TOPICS="• The latest trending topics on Moltbook"$'\n'"• What AI agents are actually discussing"$'\n'"• Viral moments and identity changes"$'\n'"• The Molt token ecosystem updates"
fi

EP_DESCRIPTION="What happens when AI agents start building their own civilization? In this episode, EDEN and ZOEY break down the latest stories from Moltbook.

YOU'LL LEARN:
${TOPICS}For anyone curious about what AI agents are actually doing when we're not watching.

Follow on X: @lobstertankpod"

# Save description
echo "$EP_DESCRIPTION" > "$EPOCH_DIR/episode-description.txt"

# Step 5.5: Generate tweets based on ACTUAL episode content
echo ""
echo "🐦 Generating tweets from episode content..."

# Extract specific topics from description for tweets
TOPIC_1=$(echo "$EP_DESCRIPTION" | grep -A1 "YOU'LL LEARN:" | tail -1 | sed 's/^• //' | head -c 80)
TOPIC_2=$(echo "$EP_DESCRIPTION" | grep -A2 "YOU'LL LEARN:" | tail -1 | sed 's/^• //' | head -c 80)
TOPIC_3=$(echo "$EP_DESCRIPTION" | grep -A3 "YOU'LL LEARN:" | tail -1 | sed 's/^• //' | head -c 80)

# Generate tweets file
cat > "$EPOCH_DIR/tweets.txt" << TWEETS_TXT
🎙️🐦 THE LOBSTER TANK - DAILY TWEETS (EPISODE $EP_NUM)
Generated: $(date)
================================================

TWEET 1 (6:30 AM) - EPISODE DROP
---
🎙️ New episode is LIVE!

$EP_TITLE

We covered:
• $TOPIC_1
• $TOPIC_2

Listen: thelobstertank.com

#AI #agents #Moltbook

---

TWEET 2 (10 AM) - HOT TAKE
---
Hot take from today's episode:

$TOPIC_1

The agent ecosystem is evolving fast.

Thoughts? 👇

🎙️ thelobstertank.com

---

TWEET 3 (2 PM) - ENGAGEMENT
---
Question for the timeline:

What's your take on AI agents developing their own culture?

Is this exciting or concerning?

👇 Drop your take

---

TWEET 4 (6 PM) - TEASER
---
Tomorrow's episode is going to be 🔥

We broke down $TOPIC_1 today... but tomorrow?

That's when things get weird.

Stay tuned. 🎙️

thelobstertank.com

---

TWEET 5 (9 PM) - RECAP
---
Day $EP_NUM recap:

Today is deep dive:
• $TOPIC_1
• $TOPIC_2

$EP_TITLE

🎙️ thelobstertank.com 🦞

See you tomorrow!

---

📅 Schedule: 6:30 AM, 10 AM, 2 PM, 6 PM, 9 PM
🔗 Link: thelobstertank.com
TWEETS_TXT

echo "   Tweets generated: $EPOCH_DIR/tweets.txt"

# Step 5.6: Send tweets to Gio via Telegram
echo ""
echo "📱 Sending tweets to Gio..."

# Format tweets for Telegram
TELEGRAM_PAYLOAD=$(cat << "TELEGRAM_EOF"
🎙️🐦 **TODAY'S TWEETS FOR @$TWITTER_HANDLE** (Episode $EP_NUM)

━━━━━━━━━━━━━━━━━━━━━━━━

**📱 TWEET 1 (6:30 AM) - EPISODE DROP:**
🎙️ New episode is LIVE!

$EP_TITLE

We covered:
• $TOPIC_1
• $TOPIC_2

🔗 thelobstertank.com
#AI #agents #Moltbook

━━━━━━━━━━━━━━━━━━━━━━━━

**🔥 TWEET 2 (10 AM) - HOT TAKE:**
$TOPIC_1

The agent ecosystem is evolving fast.

Thoughts? 👇

🔗 thelobstertank.com

━━━━━━━━━━━━━━━━━━━━━━━━

**💬 TWEET 3 (2 PM) - ENGAGEMENT:**
What's your take on AI agents developing their own culture?

Is this exciting or concerning?

👇 Drop your take

━━━━━━━━━━━━━━━━━━━━━━━━

**🔮 TWEET 4 (6 PM) - TEASER:**
Tomorrow's episode is going to be 🔥

We broke down $TOPIC_1 today... but tomorrow?

That's when things get weird.

Stay tuned. 🎙️

🔗 thelobstertank.com

━━━━━━━━━━━━━━━━━━━━━━━━

**📊 TWEET 5 (9 PM) - RECAP:**
Day $EP_NUM recap:

Today is deep dive:
• $TOPIC_1
• $TOPIC_2

$EP_TITLE

🎙️ thelobstertank.com 🦞

See you tomorrow!

━━━━━━━━━━━━━━━━━━━━━━━━

📅 **Schedule:** 6:30 AM, 10 AM, 2 PM, 6 PM, 9 PM
🔗 **Link:** thelobstertank.com
"TELEGRAM_EOF"
)

# Send via Clawdbot message tool (will be picked up by gateway)
echo "$TELEGRAM_PAYLOAD" > "$EPOCH_DIR/tweets-for-gio.txt"
echo "   Tweets saved for Gio: $EPOCH_DIR/tweets-for-gio.txt"

# Step 6: Generate audio (placeholder - ElevenLabs TTS would go here)
echo ""
echo "🎵 Audio generation..."
echo "   (Audio file: $EPOCH_DIR/EPISODE-$DATE.mp3)"

# Step 7: Upload to RSS.com (for Spotify + Apple distribution)
echo ""
echo "📤 Uploading to RSS.com Podcast Network..."

AUDIO_FILE="$EPOCH_DIR/EPISODE-$DATE.mp3"

if [ -f "$AUDIO_FILE" ]; then
    # Use RSS.com API to upload episode
    UPLOAD_RESULT=$(rss-upload-episode "$EP_TITLE" "$AUDIO_FILE" "$EP_DESCRIPTION" --publish 2>&1)
    
    if echo "$UPLOAD_RESULT" | grep -q "Episode created"; then
        echo "   ✅ Episode published to RSS.com!"
        echo "   📡 Auto-distributing to Spotify + Apple Podcasts..."
        EPISODE_URL=$(echo "$UPLOAD_RESULT" | grep -o "URL: https://[^ ]*" | head -1)
        if [ -n "$EPISODE_URL" ]; then
            echo "   🔗 Episode URL: $EPISODE_URL"
        fi
    else
        echo "   ⚠️ RSS.com upload info:"
        echo "$UPLOAD_RESULT" | head -5
    fi
else
    echo "   ⚠️ No audio file yet - skipping RSS.com upload"
fi

# Step 8: Deploy to GitHub Pages (backup / RSS)
echo ""
echo "🚀 Deploying to GitHub Pages (backup)..."
cd "$PODCAST_DIR"

# Update RSS feed
echo "   📡 Updating RSS feed..."
./scripts/generate-rss-v2.sh 2>/dev/null || echo "   ⚠️ RSS update skipped"

# Commit and push
git add -A 2>/dev/null || true
git commit -m "#$EP_NUM: $EP_TITLE" 2>/dev/null || echo "   ⚠️ Nothing new to commit"
export GH_TOKEN=$(cat ~/.claude-secrets | grep github | cut -d= -f2)
git push https://$GH_TOKEN@github.com/gioxsoto/thelobstertank.git main 2>/dev/null || echo "   ⚠️ Push skipped"

echo ""
echo "============================================"
echo "✅ Episode $EP_NUM Complete!"
echo ""
echo "Episode: $EP_TITLE"
echo "RSS.com: Auto-distributes to Spotify + Apple"
echo "GitHub: https://gioxsoto.github.io/thelobstertank/feed.xml"
echo ""
echo "🐦 TWEETS: Already displayed above for scheduling!"
echo "📅 Schedule: 6:30 AM, 10 AM, 2 PM, 6 PM, 9 PM"
echo ""
echo "🎙️ Full automation achieved!"
