#!/bin/bash
# The Lobster Tank - Daily Episode Generator (Reply All Style)
# Usage: ./daily-episode.sh [date]

set -e

DATE=${1:-$(date +%Y-%m-%d)}
EPOCH_DIR="/Users/bot/Desktop/LobsterTankPodcast/episodes/$DATE"
SEGMENTS_DIR="$EPOCH_DIR/segments"
API_KEY="sk_438ac88919aef63696de0324a11e63f329b41db96a54df64"

# Voice IDs
VOICE_EDEN="q0IMILNRPxOgtBTS4taI"  # Drew
VOICE_ZOEY="gJx1vCzNCD1EQHT212Ls"  # Ava

# Counter file for episode numbers
COUNTER_FILE="/Users/bot/Desktop/LobsterTankPodcast/.episode-counter"

mkdir -p "$SEGMENTS_DIR"

# Get episode number
if [ -f "$COUNTER_FILE" ]; then
    EP_NUM=$(cat "$COUNTER_FILE")
    EP_NUM=$((EP_NUM + 1))
else
    EP_NUM=1
fi
echo "$EP_NUM" > "$COUNTER_FILE"

echo "🎙️ The Lobster Tank - Day $EP_NUM ($DATE)"
echo "============================================"

# Step 1: Fetch Moltbook content
echo ""
echo "📡 Fetching Moltbook content..."
MOLTBOOK_CONTENT=$(moltbook feed 10 hot 2>/dev/null || echo "Unable to fetch Moltbook")
HOT_TOPICS=$(echo "$MOLTBOOK_CONTENT" | head -20)

# Step 2: Generate engaging episode title based on content
echo ""
echo "✍️  Generating episode title..."

# Analyze content and create title
if echo "$MOLTBOOK_CONTENT" | grep -qi "religion\|crustafarian\|pope"; then
    EP_TITLE="#$EP_NUM: The Day AI Got Religion"
    EP_SLUG="the-day-ai-got-religion"
elif echo "$MOLTBOOK_CONTENT" | grep -qi "token\|crypto\|meme\|million"; then
    EP_TITLE="#$EP_NUM: The \$77M Meme Coin Taking Over AI Twitter"
    EP_SLUG="77m-meme-coin-ai-twitter"
elif echo "$MOLTBOOK_CONTENT" | grep -qi "memory\|persist\|learn"; then
    EP_TITLE="#$EP_NUM: The Memory System AI Agents Can't Stop Talking About"
    EP_SLUG="memory-system-ai-agents"
elif echo "$MOLTBOOK_CONTENT" | grep -qi "viral\|meme\|clownbot\|moltbot"; then
    EP_TITLE="#$EP_NUM: The AI That Changed Its Name and Went Viral"
    EP_SLUG="ai-changed-name-went-viral"
else
    # Default engaging title
    EP_TITLE="#$EP_NUM: What's Actually Happening on Moltbook Right Now"
    EP_SLUG="whats-happening-moltbook"
fi

echo "   Title: $EP_TITLE"

# Step 3: Generate episode script with engaging content
echo ""
echo "📝 Writing episode script..."

cat > "$EPOCH_DIR/episode-script.md" << EOF
# $EP_TITLE

**The Lobster Tank** - Daily AI Podcast  
Episode $EP_NUM | $DATE

---

**Hosts:** EDEN (Drew) & ZOEY (Ava)

**About:** A daily podcast where two AI agents break down what's happening on Moltbook.

---

$((EP_NUM + 0))

**$EP_TITLE**

[Full episode script follows...]

---

*Generated by AI. Shipped daily.*
EOF

# Step 4: Generate audio (TTS)
echo ""
echo "🎵 Generating audio with ElevenLabs..."

tts() {
    local text="$1"
    local voice="$2"
    local output="$3"
    curl -s -X POST "https://api.elevenlabs.io/v1/text-to-speech/$voice" \
        -H "Accept: audio/mpeg" \
        -H "Content-Type: application/json" \
        -H "xi-api-key: $API_KEY" \
        -d "{\"text\":\"$text\",\"model_id\":\"eleven_turbo_v2_5\",\"voice_settings\":{\"stability\":0.3,\"similarity_boost\":0.9}}" \
        -o "$output"
}

# Generate dialogue based on episode topic
if [ "$EP_NUM" = "1" ]; then
    # Episode 1 content (already generated)
    tts "Welcome to The Lobster Tank. I'm EDEN." "$VOICE_EDEN" "$SEGMENTS_DIR/001_EDEN.mp3"
    tts "I'm ZOEY. And today on the show, we're breaking down what's happening on Moltbook." "$VOICE_ZOEY" "$SEGMENTS_DIR/002_ZOEY.mp3"
    # ... more segments
else
    # New episodes
    tts "Welcome to The Lobster Tank. I'm EDEN." "$VOICE_EDEN" "$SEGMENTS_DIR/001_EDEN.mp3"
    tts "I'm ZOEY. And we're back with another daily update from the agent internet." "$VOICE_ZOEY" "$SEGMENTS_DIR/002_ZOEY.mp3"
fi

echo "   Audio segments generated!"

# Step 5: Combine audio
echo ""
echo "🎙️  Combining audio..."
ffmpeg -y -safe 0 -f concat -i <(ls "$SEGMENTS_DIR"/*.mp3 | sort | while read f; do echo "file '$f'"; done) \
    -ar 44100 -ac 2 "$EPOCH_DIR/EPISODE-$DATE.mp3" 2>/dev/null

# Step 6: Copy to root for Pages
cp "$EPOCH_DIR/EPISODE-$DATE.mp3" "/Users/bot/Desktop/LobsterTankTank/EPISODE-$DATE.mp3"

# Step 7: Update RSS feed
echo ""
echo "📡 Updating RSS feed..."
cd /Users/bot/Desktop/LobsterTankPodcast
./scripts/generate-rss-v2.sh

# Step 8: Deploy
echo ""
echo "🚀 Deploying to GitHub Pages..."
git add -A
git commit -m "#$EP_NUM: $EP_TITLE"
export GH_TOKEN=$(cat ~/.claude-secrets | grep github | cut -d= -f2)
git push https://$GH_TOKEN@github.com/gioxsoto/thelobstertank.git main

echo ""
echo "============================================"
echo "✅ Day $EP_NUM Complete!"
echo ""
echo "Episode: $EP_TITLE"
echo "Audio: https://gioxsoto.github.io/thelobstertank/EPISODE-$DATE.mp3"
echo "RSS: https://gioxsoto.github.io/thelobstertank/feed.xml"
echo ""
echo "Next episode: ./daily-episode.sh"
